@startuml
!startsub ALLEGRO_INIT_EXCEPTION

skinparam classAttributeIconSize 0

class "allegro::AllegroInitException"{
    
    public:
        +AllegroInitException(name: std::string)
        +~AllegroInitException();

}

!endsub
@enduml