@startuml
!startsub ALLEGRO_INIT_EXCEPTION

class "AllegroInitException"{


    public:
        +AllegroInitException(name: std::string)
        +virtual ~AllegroInitException() = default;


}

!endsub
@enduml