@startuml

skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam linetype ortho

set separator ::


!includesub Sprite.puml!SPRITE
!includesub AllegroInitException.puml!ALLEGRO_INIT_EXCEPTION
!includesub ControleJogo.puml!CONTROLE_JOGO
!includesub Sprite4D.puml!SPRITE_4D
!includesub Tela.puml!TELA
!includesub Util.puml!UTIL

!includesub Estado.puml!ESTADO
!includesub Coordenada.puml!COORDENADA
!includesub Insignia.puml!INSIGNIA
!includesub Jogo.puml!JOGO
!includesub Mapa.puml!MAPA
!includesub Objeto.puml!OBJETO
!includesub Parede.puml!PAREDE
!includesub Player.puml!PLAYER
!includesub Tanque.puml!TANQUE
!includesub Tiro.puml!TIRO
!includesub EnumEstadoObjeto.puml!ENUM_ESTADO_OBJETO
!includesub EnumDirecao.puml!ENUM_DIRECAO

Allegro::Sprite4D -|> Allegro::Sprite

Allegro::ControleJogo --> Allegro::Util

Allegro::Sprite --> Allegro::Util 

Allegro::Tela --> Allegro::ControleJogo
Allegro::Tela --> Allegro::Sprite
Allegro::Tela --> Allegro::Util

Allegro::Util --> Allegro::AllegroInitException

Estado --> Jogo
Estado -[#blue]-> Allegro::ControleJogo
Estado -[#blue]-> Allegro::Tela

Insignia "1" -[#blue]-> "2" Allegro::Sprite : contém
Insignia -[#red]-|> Objeto

Jogo "1" -[#blue]-> "many" Allegro::Sprite : contém
Jogo "1" --> "many" Player : contém
Jogo "1" --> "many" Parede : contém
Jogo "1" -[#blue]-> "many" Allegro::Sprite4D : contém
Jogo "1" --> "many" Tanque : contém
Jogo "1" --> "many" Mapa : contém
Jogo "1" --> "many" Insignia : contém

Jogo --> Objeto
Jogo --> Tiro
Jogo -[#blue]-> Allegro::Tela
Jogo -[#blue]-> Allegro::ControleJogo
Jogo --> EnumEstadoObjeto
Jogo --> EnumDirecao

Objeto "1" --> "2" Coordenada : "contém"
Objeto "1" -[#blue]-> "1" Allegro::Sprite : "contém"
Objeto "1" --> "1" EnumEstadoObjeto : "contém"
Objeto "1" --> "1" EnumDirecao : "contém"

Parede -[#red]-|> Objeto
Parede --> EnumEstadoObjeto
Parede --> EnumDirecao

Player -down[#red]-|> Tanque
Player -[#blue]-> Allegro::Sprite4D
Player -[#blue]-> Allegro::Sprite
Player -[#blue]-> Allegro::ControleJogo
Player --> EnumDirecao
Player --> EnumEstadoObjeto
Player --> Tiro

Tanque -[#red]--|> Objeto
Tanque "1" --> "2" Allegro::Sprite4D : contém
Tanque --> Tiro
Tanque -[#blue]-> Allegro::Sprite
Tanque -[#blue]-> Allegro::Sprite4D
Tanque --> EnumDirecao
Tanque --> EnumEstadoObjeto

Tiro -[#red]-|> Objeto
Tiro "1" -[#blue]-> "1" Allegro::Sprite4D : contém
Tiro --> Parede
Tiro --> Tanque
Tiro --> EnumDirecao
Tiro --> EnumEstadoObjeto

legend right
    |Cor de Seta| Tipo |
    |<#blue>| Relações de fora para dentro do namespace allegro |
    |<#red>| Relações de herança |
endlegend

hide methods
hide attributes

@enduml