@startuml
!startsub INSIGNIA

skinparam classAttributeIconSize 0

class "insignia"{


    public:
        Insignia(x: const unsigned int, y: const unsigned int, tamanhoSprite: const unsigned short int, imortal: const unsigned short, estado:  EnumEstadoObjeto, vida: const unsigned short, velocidade: const unsigned short, direcao: EnumDirecao, spriteVivo: Allegro::Sprite *, spriteMorto: Allegro::Sprite *)
        
        atualizarSprite(): void 

    private:
        spriteVivo: Allegro::Sprite *
        spriteMorto: Allegro::Sprite *


}

!endsub
@enduml