@startuml
!startsub SPRITE

skinparam classAttributeIconSize 0

class "Allegro::Sprite"{
<<constructor>> Sprite()
<<constructor>> Sprite(fileName: const std::string &)
<<constructor>> Sprite(sprite: const Sprite *, inicioX: const unsigned int, inicioY: const unsigned int, larg: const unsigned int, alt: const unsigned int)
<<destructor>> ~Sprite()

+ ALLEGRO_BITMAP *getBitmap() const
# void setBitmap(bitmap: ALLEGRO_BITMAP* const);
# ALLEGRO_BITMAP *bitmap; 
}

!endsub
@enduml